# Generated by Django 5.1.3 on 2025-05-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='./static/media/'),
        ),
    ]
